### ISSUE TITLE
README  improvements

### ISSUE THREAD

**Issue by gyorgybalazsi** [digital-asset/daml-on-fabric#23]
I would suggest a couple of improvements to the README file. 

**Dependencies**:

Docker CE 19.x version is also ok
Scala and SBT version doesn't really matter because they are defined in the project, you need an SBT which in the background downloads the specified versions.
Fabric and Fabric SDK is not a real prerequisite, because you download everything needed during the steps specified later.

**Cloning DAML-on-Fabric**

For the sake of cleanliness, we are using the directory ~/daml-on-fabric as the root for the repository.

$ cd
$ git clone git@github.com:digital-asset/daml-on-fabric.git

^^^^ The line above is the SSH link which doesn't work if you didn't put an SSH key in your repo, the HTTPS link is more universal.

**Running Java Quick Start against DAML-on-Fabric**

In this section the path definitions are mismatched. Two scenarios are mixed: 1) you download the quickstart project withing your daml-on-fabric folder, or 2) you download the quickstart project into you home directory.

This is the correct version for the case when you download the quickstart project into your home directory:

Step 2. Extract and build Quick Start project

$ cd  (not cd ~/daml-on-fabric )
$ rm -rf quickstart
$ daml new quickstart quickstart-java
Created a new project in "quickstart" based on the template "quickstart-java".
$ cd ~/quickstart/
$ daml build
Compiling daml/Main.daml to a DAR
Created .daml/dist/quickstart-0.0.1.dar

Step 3. Run the Ledger with Quick Start DAR archive

$ cd ~/daml-on-fabric/
$ sbt "run --port 6865 --role provision,time,ledger,explorer ~/quickstart/.daml/dist/quickstart-0.0.1.dar" (not ./quickstart/.daml/dist/quickstart-0.0.1.dar)

Step 4. Run DAML Navigator

$ cd ~/quickstart/
daml navigator server localhost 6865 --port 4000

Step 5. Allocate parties on the ledger

There's no automatic mapping of DAML parties to parties on the Fabric ledger. We'll need to create the parties on Fabric that match the party names in DAML:

$ cd ~/quickstart/
daml ledger allocate-parties --host localhost --port 6865 Alice Bob Carol USD_Bank EUR_Bank

**Comment by dasormeter** [comment]
thanks for the feedback @gyorgybalazsi! : will update based on these suggestions
