### ISSUE TITLE
Quickstart fails with error in `sbt`

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml-on-fabric#57]
When I follow the setup instructions from the README, the `sbt` command fails with

```
[error] (run-main-0) com.daml.FabricContextException: response {
[error]   status: 500
[error]   message: "make sure the chaincode daml_on_fabric has been successfully defined on channel mainchannel and try again: chaincode daml_on_fabric not found"
[error] }
```

Logs for fabric and sbt attached.
[sbt.log](https://github.com/digital-asset/daml-on-fabric/files/5696642/sbt.log)
[fabric.log](https://github.com/digital-asset/daml-on-fabric/files/5696651/fabric.log)

**Comment by bame-da** [comment]
The issue for me as the one discussed in https://github.com/docker/for-mac/issues/4955. In the latest versions of Docker Desktop for Mac OS X one has to disable "Use gPRC FUSE for file sharing" in the Experimental Features section of the Preferences..

**Comment by dasormeter** [comment]
NOTE added to README to ensure `Enable gRPC FUSE` is not enabled in docker client, as that is problematic for the hyperledger fabric components
