### ISSUE TITLE
How to get fabric block number through daml?

### ISSUE THREAD

**Issue by HarshMultani** [digital-asset/daml-on-fabric#66]
Hi @digitalasset-cla, @dasormeter,

I am using daml on fabric, and wanted to know whether there is a way of retrieving fabric block number through daml code?

**Comment by dasormeter** [comment]
Hi @HarshMultani DAML will not expose the underlying Fabric block number details -- all read and write access to the underlying ledger is via the gRPC Ledger API

**Comment by HarshMultani** [comment]
Thanks @dasormeter
