### ISSUE TITLE
Daml template issue on daml on fabric?

### ISSUE THREAD

**Issue by HarshMultani** [digital-asset/daml-on-fabric#68]
Hi @dasormeter, @anthonylusardi-da.

I was running daml on fabric.
Had one scenario for question :-

Suppose consider, that I have a template :-

module ExampleModule where

template Example
     with
           admin: Party
           variable: Text
     where
          signatory admin

And now, I have deployed dar file related to this using daml runtime on fabric.

Now, I want to change the template and add additional field (The module name and the template name would be same)

module ExampleModule where

template Example
     with
           admin: Party
           variable: Text
           active: Bool
     where
          signatory admin

Now, I deployed this using daml runtime on the same fabric network as was earlier.

And so, it would have 2 templateIds by the same name (ExampleModule:Example).
So, would it be able to resolve as to which daml contract to create or retrieve?

I last checked, it was not able to resolve as they had similiar names, Is there a workaround for this or is it not right to update templates in this manner?

**Comment by anthonylusardi-da** [comment]
Hi @HarshMultani I moved this question to our forum discuss.daml.com and [you can see it here](https://discuss.daml.com/t/will-there-be-naming-conflicts-if-i-upgrade-my-contracts-on-daml-on-fabric-or-any-ledger/2161). If you don't have a forum account account already it would be good to get one to ask questions on using and programming in Daml this as GitHub Issues are for bugs and feature requests in Daml.
